#!/usr/bin/env bash
# Create the cc* shortcut commands and make sure they're on PATH.
# Safe to re-run: it always rewrites the shortcuts so updates land.

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BIN_DIR="$HOME/.local/bin"

echo -e "${BLUE}Setting up easy launch shortcuts...${NC}\n"

# Each entry: name|description|command to run inside the install directory
SHORTCUTS=(
    "ccdocker|Launch Claude Code CLI|./scripts/launchers/run_claude.sh \"\$@\""
    "ccvscode|Launch VS Code Server (browser IDE)|./scripts/launchers/run_vscode.sh \"\$@\""
    "ccauth|Set up or change how you sign in|./scripts/installers/setup-credentials.sh \"\$@\""
    "ccstop|Stop the container|./scripts/launchers/run_claude.sh stop"
    "ccrestart|Restart the container|./scripts/launchers/run_claude.sh restart"
    "cclogs|View container logs|./scripts/launchers/run_claude.sh logs"
    "ccdiagnose|Check the install for problems|./scripts/maintenance/diagnose.sh"
    "ccbackup|Back up your workspace|./scripts/maintenance/backup.sh \"\$@\""
    "ccpath|Change which folder is your workspace|./scripts/maintenance/set-workspace.sh \"\$@\""
    "ccupdate|Update to the latest version|./scripts/maintenance/update.sh"
)

setup_bin_scripts() {
    mkdir -p "$BIN_DIR"

    # Always rewrite. The old version bailed out if ccvscode already existed,
    # which meant existing installs never received newly added shortcuts (like
    # ccauth) or fixes to the ones they had.
    local entry name desc cmd
    for entry in "${SHORTCUTS[@]}"; do
        IFS='|' read -r name desc cmd <<< "$entry"

        cat > "$BIN_DIR/$name" << EOF
#!/usr/bin/env bash
# $desc — generated by cc-install, safe to delete.
set -euo pipefail
cd "$INSTALL_DIR" || {
    echo "cc-install is no longer at $INSTALL_DIR" >&2
    echo "Reinstall, or delete this shortcut: rm $BIN_DIR/$name" >&2
    exit 1
}
exec $cmd
EOF
        chmod +x "$BIN_DIR/$name"
    done

    echo -e "${GREEN}✓${NC} Created shortcuts in $BIN_DIR"
    for entry in "${SHORTCUTS[@]}"; do
        IFS='|' read -r name desc cmd <<< "$entry"
        printf "  ${BLUE}%-11s${NC} %s\n" "$name" "$desc"
    done
}

# Ensure ~/.local/bin is on PATH for future shells (idempotent + self-healing)
ensure_local_bin_on_path() {
    local path_marker="# Added by cc-install (Claude Code) — enables ccdocker/ccvscode"
    local path_line='export PATH="$HOME/.local/bin:$PATH"'

    # Pick the startup file for the user's LOGIN shell (from $SHELL), NOT the
    # shell running this script. The installer runs this under bash, so
    # $BASH_VERSION / $ZSH_VERSION here describe the installer — not the user's
    # real interactive shell — and must not be used to choose the rc file.
    local login_shell="${SHELL##*/}"
    local rc_file=""
    case "$login_shell" in
        zsh)  rc_file="$HOME/.zshrc" ;;
        bash)
            if [ "$(uname)" = "Darwin" ]; then
                rc_file="$HOME/.bash_profile"   # macOS login shells read this
            else
                rc_file="$HOME/.bashrc"
            fi
            ;;
        *)
            if [ "$(uname)" = "Darwin" ]; then
                rc_file="$HOME/.zshrc"          # macOS default shell is zsh
            else
                rc_file="$HOME/.profile"
            fi
            ;;
    esac

    if [ -f "$rc_file" ] && grep -qF '.local/bin' "$rc_file"; then
        echo -e "${GREEN}✓${NC} PATH already set up in $rc_file"
        return
    fi

    {
        echo ""
        echo "$path_marker"
        echo "$path_line"
    } >> "$rc_file"

    echo -e "${GREEN}✓${NC} Added ~/.local/bin to your PATH in $rc_file"
    echo -e "  ${YELLOW}Open a NEW Terminal window${NC} to use ${BLUE}ccdocker${NC} / ${BLUE}ccvscode${NC}"
    echo -e "  (or, in this window, run: ${BLUE}source $rc_file${NC})"
}

# macOS: a double-clickable app that opens Claude Code in Terminal.
create_macos_app() {
    [ "$(uname)" = "Darwin" ] || return 0

    local app_dir="$HOME/Applications/Claude Code.app"
    mkdir -p "$app_dir/Contents/MacOS"

    # Unquoted heredoc so $INSTALL_DIR is baked in NOW. With a quoted heredoc
    # the literal string "$INSTALL_DIR" ended up in the generated script, where
    # it expanded to nothing and the app just cd'd to the home directory.
    cat > "$app_dir/Contents/MacOS/claude-code" << EOF
#!/bin/bash
# Generated by cc-install.
osascript -e 'tell application "Terminal" to do script "cd \"$INSTALL_DIR\" && ./bin/claude"' \\
          -e 'tell application "Terminal" to activate'
EOF
    chmod +x "$app_dir/Contents/MacOS/claude-code"

    cat > "$app_dir/Contents/Info.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>claude-code</string>
    <key>CFBundleIdentifier</key>
    <string>edu.virginia.batten.claudecode</string>
    <key>CFBundleName</key>
    <string>Claude Code</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
</dict>
</plist>
EOF

    echo -e "${GREEN}✓${NC} Created ~/Applications/Claude Code.app"
}

print_instructions() {
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Shortcuts ready${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  ${GREEN}ccauth${NC}     ← run this first, to set up how you sign in"
    echo -e "  ${GREEN}ccdocker${NC}   Claude Code in your terminal"
    echo -e "  ${GREEN}ccvscode${NC}   VS Code in your browser"
    echo ""
    if [ "$(uname)" = "Darwin" ]; then
        echo -e "  macOS: also in ~/Applications as ${YELLOW}Claude Code${NC}"
        echo ""
    fi
    echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
}

setup_bin_scripts
ensure_local_bin_on_path
create_macos_app
print_instructions
